# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField()),
                ('left_message', models.BooleanField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('stage', models.CharField(choices=[('GET_INFO', 'Gather contact information'), ('SEND_LETTER', 'Need to send letter'), ('CALL', 'Need to call'), ('MEET', 'Meeting scheduled'), ('THANK', 'Send thank you'), ('FOLLOW_UP', 'Need to follow up'), ('STOP', 'Do not pursue further'), ('WAIT', 'Wait for a period of time'), ('MAINTAIN', 'Maintain')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mailed', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('spouse_name', models.CharField(max_length=120)),
                ('phone_number', models.BigIntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachussets'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_referred', models.DateField()),
                ('referred_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person')),
                ('referring_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='supporttracker.Person')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('spouse_name', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachussets'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('SEMI_ANNUALLY', 'Semi-annually'), ('ONE_TIME', 'One-time')], max_length=255)),
                ('start_date', models.DateField()),
                ('staff_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.StaffPerson')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ThankYou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField()),
                ('note', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person')),
                ('staff_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.StaffPerson')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_left', models.DateTimeField()),
                ('note', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person')),
                ('staff_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.StaffPerson')),
            ],
        ),
        migrations.AddField(
            model_name='referral',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.StaffPerson'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.StaffPerson'),
        ),
        migrations.AddField(
            model_name='letter',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person'),
        ),
        migrations.AddField(
            model_name='letter',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.StaffPerson'),
        ),
        migrations.AddField(
            model_name='contactrelationship',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person'),
        ),
        migrations.AddField(
            model_name='contactrelationship',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.StaffPerson'),
        ),
        migrations.AddField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person'),
        ),
        migrations.AddField(
            model_name='call',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.StaffPerson'),
        ),
    ]
