# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supporttracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('spouse_name', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachussets'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('zip', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='call',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='contactrelationship',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='supportrelationship',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='thankyou',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile'),
        ),
    ]
