# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0005_auto_20160419_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrelationship',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually'), ('Semi-annually', 'Semi-annually'), ('One-time', 'One-time')], max_length=255),
        ),
    ]
