# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0006_auto_20160419_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrelationship',
            name='date_entered',
            field=models.DateField(default=datetime.datetime(2016, 4, 19, 19, 5, 40, 755000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
