# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0008_auto_20160420_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 4, 20, 20, 21, 30, 571000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
