# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0011_auto_20160421_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
