# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0012_call_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrelationship',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
