# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0013_supportrelationship_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='note',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactrelationship',
            name='stage',
            field=models.CharField(choices=[('GET_INFO', 'Gather contact information'), ('SEND_LETTER', 'Need to send letter'), ('MESSAGE', 'Need to send email/Facebook'), ('CALL', 'Need to call'), ('MEET', 'Meeting scheduled'), ('THANK', 'Send thank you'), ('FOLLOW_UP', 'Need to follow up'), ('STOP', 'Do not pursue further'), ('WAIT', 'Wait for a period of time'), ('MAINTAIN', 'Maintain')], max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True),
        ),
    ]
