# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0014_auto_20160428_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
