# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0015_auto_20160428_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_date', models.DateField()),
                ('date_added', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person')),
                ('staff_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='contactrelationship',
            name='referral_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactrelationship',
            name='referred_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred', to='supporttracker.Person'),
        ),
    ]
