# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0016_auto_20160429_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person')),
                ('staff_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile')),
            ],
        ),
    ]
