# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0018_reminder_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_send', models.DateField()),
                ('date_entered', models.DateField(default=datetime.date.today)),
                ('method', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('sent', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person')),
                ('staff_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile')),
            ],
        ),
    ]
