# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0019_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 6, 15, 23, 22, 890000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
