# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0021_auto_20160506_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('method', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.Person')),
                ('staff_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporttracker.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='contactrelationship',
            name='stage',
            field=models.CharField(choices=[('GET_INFO', 'Gather contact information'), ('MESSAGE', 'Need to send letter/message'), ('CALL', 'Need to call'), ('MEET', 'Meeting scheduled'), ('THANK', 'Send thank you'), ('FOLLOW_UP', 'Need to follow up'), ('STOP', 'Do not pursue further'), ('WAIT', 'Wait for a period of time'), ('MAINTAIN', 'Maintain')], max_length=255),
        ),
    ]
