# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0022_auto_20160509_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thankyou',
            old_name='date_sent',
            new_name='date',
        ),
        migrations.AddField(
            model_name='thankyou',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
