# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporttracker', '0025_call_voice_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='yearly_support_goal',
            field=models.IntegerField(default=54516),
        ),
        migrations.AlterField(
            model_name='supportrelationship',
            name='date_entered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supportrelationship',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
